name: Tests 

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Install dependencies (gcc, make, etc.)
      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential libsodium-dev

      # Build
      - name: Build project
        run: |
          make 
      # Run tests
      - name: Run tests
        run: |
          make test 
