name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt-get update && sudo apt-get install -y build-essential libsodium-dev

      # Restore cached object files + binary
      - name: Restore build cache
        uses: actions/cache/restore@v4
        with:
          path: |
            TapIn         
            src/**/*.o        # add subdirs if needed
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.c', '**/*.h', 'Makefile') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Build project
        run: make -j$(nproc)

      # Save updated cache
      - name: Save build cache
        if: always()
        uses: actions/cache/save@v4
        with:
          path: |
            TapIn 
            src/**/*.o
          key: ${{ runner.os }}-build-${{ hashFiles('**/*.c', '**/*.h', 'Makefile') }}

      - name: Run tests
        run: make test

